### ISSUE TITLE
Switch_OR idea

### ISSUE THREAD

**Issue by FrozenVoid** [Gigantua/Chess_Movegen#2]
Alternative to switch.hpp
```	switch (SliderSquare) {
		case 0:
			result = 2ull;
			if ((occupy & 2ull) == 0) result |= 4ull;
			if ((occupy & 6ull) == 0) result |= 8ull;
			if ((occupy & 14ull) == 0) result |= 16ull;
			if ((occupy & 30ull) == 0) result |= 32ull;
			if ((occupy & 62ull) == 0) result |= 64ull;
			if ((occupy & 126ull) == 0) result |= 128ull;
			return result;
``` 
can be replaced 
with something like
(result array)
```
return result[0]|((((occupy & 2ull) == 0)* 4ull)|(((occupy & 6ull) == 0) *8ull)|...
 
//as single expression since |0 doesn't change result

```

**Comment by Gigantua** [comment]
Interesting Idea!
result = (occupy & 126ull) == 0) << 7 | ((occupy & 62ull) == 0) << 6 | (occupy & 30ull) == 0) << 5 .....

**Comment by FrozenVoid** [comment]
i think all these (occupy & 30ull) expressions can also be generalized into arrays: 

result[x] |((occupy & arr[x][1])==0)*arr[x][0]|...

that would allow to replace switch with
a single expression for all cases regardless
of number of ORs(using |0 ), which in theory
 would be faster.

**Comment by Gigantua** [comment]
Interesting - maybe I will add a new backend for https://github.com/Gigantua/Espresso
to emit these arrays automatically. 

Looking up into arrays on x64 is generally a little bit faster compared to execution jumps inside the switch.

**Comment by FrozenVoid** [comment]
The expression can be simplified to:
```
((occupy & arr[x][1])==0)*arr[x][0]
arr[x][0] & (0 or ~0)
             if 0 ->1->0-1=0xfff...&x==x
             if >0 ->0 ->0-0=0&x=0
arr[x][0] & (0ULL -(!(occupy & arr[x][1]))
with 0ULL- can be simplified further
due 2's complement format in all current machine as
arr[x][0] & ( -(!(occupy & arr[x][1]))
since in 2's complement (-1) unsigned is 0xffff..


```
(if all numbers are in form of 1<<x, then `!(occupy & arr[x][1]) << x` might be faster, but shift latencies on some processors will negate this)

**Comment by Gigantua** [comment]
@FrozenVoid could you send a PR for that change?
I am 100% certain that it will be faster. 

If you only send a single changed switch that would help also.

**Comment by FrozenVoid** [comment]
I cannot run your code i only have
 GCC8.3 and this linux version doesn't
 support anything more recent.

**Comment by Gigantua** [comment]
GCC8.3 should support c++20.
If there are compilation errors please share!
This should compile on every target architecture out there.

**Comment by FrozenVoid** [comment]
```
make
clang++ -O3 -mllvm -inline-threshold=16000 -fdeclspec -march=native -funroll-loops -std=c++20 -pthread Main.cpp -o movegen_compare
make: clang++: Command not found
make: *** [Makefile:7: all] Error 127
```
for gcc
```
gcc Main.cpp
In file included from Main.cpp:235:
GeneticObstructionDiff.hpp:22:10: fatal error: bit: No such file or directory
 #include <bit>
          ^~~~~
compilation terminated.
```

**Comment by Gigantua** [comment]
Oh that is indeed an issue that could only be fixed by updating the compiler. 
Closed!

**Comment by FrozenVoid** [comment]
```
g++  Main.cpp
In file included from Main.cpp:235:
GeneticObstructionDiff.hpp:22:10: fatal error: bit: No such file or directory
 #include <bit>
          ^~~~~
compilation terminated.
```
clang-11
```
clang++-11 -std=c++2a -O3  Main.cpp 
In file included from Main.cpp:235:
./GeneticObstructionDiff.hpp:22:10: fatal error: 'bit' file not found
#include <bit>
         ^~~~~
1 error generated.
```
